#!/bin/sh

DATA_FOLDER="data"
CACHE_FOLDER="cache"

if [ $BILLML_BACKUP_BILLS_DATA_CLOUD_PROVIDER = "s3" ]
    then
        # sync bills data
        BILLS_LOCAL_PATH=$CONGRESS_DATA_FOLDER_FILEPATH
        BILLS_BUCKET_PATH=s3://$BILLML_BACKUP_BILLS_DATA_BUCKET_NAME/$DATA_FOLDER
        echo "Syncing bills data path: '$BILLS_LOCAL_PATH' with the cloud storage: '$BILLS_BUCKET_PATH'"
        AWS_ACCESS_KEY_ID=$BILLML_BACKUP_BILLS_DATA_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$BILLML_BACKUP_BILLS_DATA_SECRET_KEY aws s3 sync $BILLS_BUCKET_PATH $BILLS_LOCAL_PATH
        # sync bills cache data
        CACHE_LOCAL_PATH=$CONGRESS_CACHE_FOLDER_FILEPATH
        CACHE_BUCKET_PATH=s3://$BILLML_BACKUP_BILLS_DATA_BUCKET_NAME/$CACHE_FOLDER
        echo "Syncing bills data path: '$CACHE_LOCAL_PATH' with the cloud storage: '$CACHE_BUCKET_PATH'"
        AWS_ACCESS_KEY_ID=$BILLML_BACKUP_BILLS_DATA_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$BILLML_BACKUP_BILLS_DATA_SECRET_KEY aws s3 sync $CACHE_BUCKET_PATH $CACHE_LOCAL_PATH
else
    echo "Non suported cloud provider: '$BILLML_BACKUP_BILLS_DATA_CLOUD_PROVIDER'"
fi
